function BandStopResult = Filter_BandStop ( frenquency, SignalSource ,fs)
%BANDSTOP Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.13 and the Signal Processing Toolbox 6.16.
%
% Generated on: 14-Nov-2013 11:27:37
%

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fpass1 = frenquency - 3;          % First Passband Frequency
Fstop1 = frenquency - 1;          % First Stopband Frequency
Fstop2 = frenquency + 1;          % Second Stopband Frequency
Fpass2 = frenquency + 3;          % Second Passband Frequency
Apass1 = 1;           % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

SOS             = Hd.sosMatrix;
G               = Hd.ScaleValues;
BandStopResult  = filtfilt(SOS, G, SignalSource);

% [EOF]
