function result= Filter_BandPass(frelow,frehigh,origin,fs)
%BANDPASS Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 18-Nov-2013 15:33:32
%

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fstop1 = frelow-15;          % First Stopband Frequency
Fpass1 = frelow;          % First Passband Frequency
Fpass2 = frehigh;         % Second Passband Frequency
Fstop2 = frehigh+50;         % Second Stopband Frequency
Astop1 = 30;     % First Stopband Attenuation (dB)
Apass  = 1;     % Passband Ripple (dB)
Astop2 = 30;     % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);
SOS             = Hd.sosMatrix;
G               = Hd.ScaleValues;
result  = filtfilt(SOS, G, origin);

% [EOF]
